version: '3.8'

services:
  youtube-sentiment-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - DEBUG=False
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
      # Mount the pre-trained model
      - ./backend/sentiment_analysis/models/sentiment_model.pkl:/app/backend/sentiment_analysis/models/sentiment_model.pkl
      # Mount these directories to persist data between runs
      - ./backend/scraper/api_key.txt:/app/backend/scraper/api_key.txt
      - ./backend/scraper/country_codes.txt:/app/backend/scraper/country_codes.txt
      - ./backend/scraper/output:/app/backend/scraper/output
    restart: unless-stopped